# RUBEN: Improve
class Prompts:
  welcome = "Welcome to restaurantpicker9000! What kind of restaurant are you looking for?"
  ask_confirm = "Did you mean '{1}' instead of '{0}'?"
  area_ask = "What area?"
  area_ask_invalid = "I don't recognize that as a valid area, choose north, east, south, west or centre. What area?"
  food_ask = "What food?"
  food_ask_invalid = "I don't recognize that as a valid food type. What food?"
  price_ask = "What price?"
  price_ask_invalid = "I don't recognize that as a valid price, choose cheap, moderate or expensive. What price?"
  additions_ask = "Do you have an additional requirement: touristic, assigned seats, children or romantic? You can also say no."
  additions_ask_invalid = "I did not recognise an additional requirement. Please choose touristic, assigned seats, children or romantic, or say no."
  suggest = "I suggest {}."
  suggest_new = "Another good option is {}."
  no_restaurant = "There are no restaurants matching your preferences."
  goodbye = "Thank you for using this system and goodbye!"
  inform = "{}"